### ISSUE TITLE
安卓14不能用了

### ISSUE THREAD

**Issue by auto-generated** [5ec1cff/StethoX#1]
小米13  pro
安卓14

升级14之前可以用升级完不能用了

**Comment by 5ec1cff** [comment]
看看 CI debug 版能不能用，不要用 release

https://github.com/5ec1cff/StethoX/actions/runs/6515320519

**Comment by auto-generated** [comment]
ci可以看到应用了，但是浏览器打开console有错误信息

```
fatal error in stetho:java.lang.IllegalStateException: Observer com.facebook.stetho.inspector.protocol.module.Page$$ExternalSyntheticLambda0@94087cf is already registered.
	at android.database.Observable.registerObserver(Observable.java:49)
	at com.facebook.stetho.inspector.jsonrpc.JsonRpcPeer.registerDisconnectReceiver(JsonRpcPeer.java:67)
	at com.facebook.stetho.inspector.protocol.module.Page.startScreencast(Page.java:167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.stetho.inspector.MethodDispatcher$MethodDispatchHelper.invoke(MethodDispatcher.java:106)
	at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:69)
	at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:142)
	at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:124)
	at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:100)
	at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:174)
	at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:134)
	at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:42)
	at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:43)
	at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:115)
	at com.facebook.stetho.websocket.WebSocketHandler.handleRequest(WebSocketHandler.java:81)
	at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:83)
	at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:60)
	at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:50)
	at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:61)
	at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:31)
	at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:34)
	at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:165)
```

**Comment by 5ec1cff** [comment]
https://github.com/5ec1cff/StethoX/actions/runs/6839061044
