### ISSUE TITLE
Not working for Android 14

### ISSUE THREAD

**Issue by IamLoot** [5ec1cff/StethoX#2]
Hello there,  First of all i would thank you about the efforts  you bring to this xposed module.

It's not working for my Android 14 device. I tried both latest CI build's debug and release version.

I selected the target app in scope and connected my device with ADB (laptop). I inspected chrome://inspect in the device section, it is showing that my device is connected via ADB. It is showing my device name too but it is not showing any URL to inspect even though I am on the webview page of the target app.

Device: OnePlus 11
Android version: 14

**Comment by 5ec1cff** [comment]
netstat -anp | grep stetho

**Comment by IamLoot** [comment]
> netstat -anp | grep stetho

![IMG_20240220_170835](https://github.com/5ec1cff/StethoX/assets/137880948/465ee3d8-feae-4a3b-a684-8ba8a21b6dcd)

**Comment by 5ec1cff** [comment]
try forward the unix socket via adb

**Comment by IamLoot** [comment]
I don't know how to do that🙁

> try forward the unix socket via adb

**Comment by 5ec1cff** [comment]
```
adb forward tcp:9222 unix-abstract:stetho_<package_name>_devtools_remote
```

and then add localhost:9222 to your port forward list

![image](https://github.com/5ec1cff/StethoX/assets/56485584/53d3ccdc-97e5-49b6-a08b-edfca6f88dfb)

**Comment by 5ec1cff** [comment]
@5ec1cff localabstract

**Comment by JasonKhew96** [comment]
```
04-10 23:39:39.055  1463  2359 W ActivityManager: Receiver with filter android.content.IntentFilter@db3429a already registered for pid 30076, callerPackage is com.twitter.android
04-10 23:39:39.056 30076 30076 E ActivityThread: Failed to find provider info for io.github.a13e300.tools.stethox.suspend
04-10 23:39:39.056 30076 30076 E StethoX : failed to find suspend provider, please ensure module process without restriction
04-10 23:39:39.056 30076 30076 E StethoX : java.lang.IllegalArgumentException: Unknown authority io.github.a13e300.tools.stethox.suspend
04-10 23:39:39.056 30076 30076 E StethoX : 	at android.content.ContentResolver.call(ContentResolver.java:2463)
04-10 23:39:39.056 30076 30076 E StethoX : 	at android.content.ContentResolver.call(ContentResolver.java:2446)
04-10 23:39:39.056 30076 30076 E StethoX : 	at io.github.a13e300.tools.StethoxAppInterceptor.g(SourceFile:1)
04-10 23:39:39.056 30076 30076 E StethoX : 	at io.github.a13e300.tools.StethoxAppInterceptor.d(SourceFile:1)
04-10 23:39:39.056 30076 30076 E StethoX : 	at io.github.a13e300.tools.StethoxAppInterceptor$a.afterHookedMethod(Unknown Source:51)
04-10 23:39:39.056 30076 30076 E StethoX : 	at MD.MgJUcTlGi.y.xm.LdFA.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
04-10 23:39:39.056 30076 30076 E StethoX : 	at G.callback(Unknown Source:294)
04-10 23:39:39.056 30076 30076 E StethoX : 	at LSPHooker_.attach(Unknown Source:11)
04-10 23:39:39.056 30076 30076 E StethoX : 	at android.app.Instrumentation.newApplication(Instrumentation.java:1346)
04-10 23:39:39.056 30076 30076 E StethoX : 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
04-10 23:39:39.056 30076 30076 E StethoX : 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1399)
04-10 23:39:39.056 30076 30076 E StethoX : 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7268)
04-10 23:39:39.056 30076 30076 E StethoX : 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
04-10 23:39:39.056 30076 30076 E StethoX : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2337)
04-10 23:39:39.056 30076 30076 E StethoX : 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-10 23:39:39.056 30076 30076 E StethoX : 	at android.os.Looper.loopOnce(Looper.java:232)
04-10 23:39:39.056 30076 30076 E StethoX : 	at android.os.Looper.loop(Looper.java:317)
04-10 23:39:39.056 30076 30076 E StethoX : 	at android.app.ActivityThread.main(ActivityThread.java:8501)
04-10 23:39:39.056 30076 30076 E StethoX : 	at java.lang.reflect.Method.invoke(Native Method)
04-10 23:39:39.056 30076 30076 E StethoX : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
04-10 23:39:39.056 30076 30076 E StethoX : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by 5ec1cff** [comment]
@JasonKhew96
